= Gravitational Waves
\
Since time immemorial, humanity has gazed at the stars. With wonder rooted deep in their minds, they imagined strange and divine mechanisms in order to try and make sense of what they saw. Over the millennium, the vast skies have revealed much about their working, and with ever-improving tools, we have come much closer to understanding their mysteries, but there is still much to be uncovered. It is unclear exactly how deep the truth lies. Perhaps we have but only scratched at the surface. The depths are so vast we simply do not know.

Almost all of that knowledge, all of that understanding, and academia has been built upon the observation of just a single type of particle. Until very recently, the only information we had about the world above us came from light, and although the humble photon has taught us a great deal about the scope of our universe, the discovery of new messengers promises pristine, untapped wells of science. It has only been in the last century that we have achieved the technological prowess to detect any other extraterrestrial sources of data except that which fell to us as meteors. We have brought rocks home from the moon @moon_rocks. We study data sent back from probes shot out across the solar system and even ones that have peaked just beyond the Sun's mighty sphere of influence @voyager. We have seen neutrinos, tiny, almost massless particles that pass through entire planets more easily than birds through the air @neutrino, and single particles with the energy of Wimbledon serve @cosmic_rays. Most recently of all, we have seen the skin of space itself quiver --- gravitational waves, the newest frontier in astronomy @first_detction.

Practical gravitational-wave astronomy is in its infancy; compared to the other fields of astrophysics, it has barely left the cradle, with the first confirmed gravitational-wave detection occurring in 2015 @first_detction. Although the field has progressed remarkably quickly since its inception, there is still a lot of work to be done --- a lot of groundwork to be performed whilst we uncover the best ways to deal with the influx of new data that we are presented with. It seems likely, assuming both funding and human civilization prevail, that work undertaken now will be but the first bricks in a great wall of discovery. New gravitational-wave observatories that are even today being planned will increase our sensitive range by orders of magnitude @einstein_telescope @cosmic_explorer @LISA. With any luck, they will open our ears further to previously undiscovered wonders.

This chapter will introduce a small part of the science of gravitational waves; it will not be an extensive review as many of the particularities are not especially relevant to the majority of the content of this thesis. Instead, this section aims to act as a brief overview to give context to the purpose behind the data-analysis methods presented throughout. We will cover the theoretical underpinning of gravitational waves, as well as a glancing tour through the experiments used to detect them.

== Gravity --- A Brief History of Down

Gravity is one of the four fundamental forces of nature, the other three being the electromagnetic force and the strong and weak nuclear forces @four_forces. It is, in some ways, the black sheep of the interactions, as it is the only one not explained by the standard model of particle physics, the most accurate theory of physics ever described @standard_model. Luckily, gravity has its own extremely accurate descriptive theory @testing_gr, even if we haven't yet tessellated it neatly with the other three forces. It has a storied history, which, if you are unfamiliar, is worth skimming for context. 

=== Ye Old Times

In the beginning, men threw rocks at each other and were entirely unsurprised when they hit the floor. Over time, people became more and more confused as to why this was the case. Many philosophers proposed many reasons why one direction should be preferred over all others when it came to the unrestrained motion of an object. For a long time, there was much confusion about the relationship between mass, density, buoyancy, and the nature and position of various celestial objects. Sometime after we had decided that the Earth was not, in fact, at the centre of the universe and that objects fell at the same speed irrespective of their densities, came the time of Sir Issac Newton, and along with him arrived what many would argue was the beginning of modern physics.

The idea of gravity as a concept had been around for many thousands of years at this point, but what Newton did was formalise the rules by which objects behaved under the action of gravity. Newton's universal law of gravitation states that all massive objects in the universe attract all others @principia_mathematica, acting upon each other, much to his displeasure, whether surrounded by a medium or not. Gravity appeared to ignore all boundaries and was described in a simple formula that seemed to correctly predict everything from the motion of the planets (mostly) to the fall of an apple

#set math.equation(numbering: "(2.1)")
$ F = (G m_1 m_2) / r^2 . $ <newtons-law-of-universal-gravitation>

where $F$ is the force along the direction between the two masses, $G$ is the gravitational constant equal to #box($6.67430(15) times 10^(−11)$ + h(1.5pt) + $m^3 "kg"^(-1) s^(-2)$) @gravitational_constant, $m_1$ is the mass of the first object, $m_2$ is the mass of the second object, and $r$ is the distance between the two objects. Newton's law of universal gravitation describes the force every massive object in the universe experiences because of every other --- an equal and opposite force proportional to the product of their two masses; see @newtons_law. Though we now know this equation to be an imperfect description of reality, it still holds accurate enough for many applications to this day.

#figure(
  image("newtons_law.png", width: 30%),
  caption: [An illustration of Newton's law of universal gravitation, as described by @newtons-law-of-universal-gravitation. Two particles, here distinguished by their unique masses $m_1$ and $m_2$ are separated by a distance, $r$. According to Newton's law, they are pulled toward each other by the force of gravity acting on each object $F$, each being pulled directly toward the other by a force that is equal and opposite to its partner's.],
) <newtons_law>

It was also around this time that a fierce debate raged over the nature of space and time. Newton proposed a universal time that ticked whether in the presence of a clock or not and a static, ever-present grid of space that never wavered nor wandered. Both would continue to exist whether the rest of the universe was there or not. Leibniz, on the other hand, argued that space and time were little more than the relations between the positions of objects and sequences of events. If there were no objects, there would be nothing to measure, and there would be no space. If there were no events, there would be nothing to time, and there would be no ticks; see @newton_vs_leibniz. At the time, they did not come to a resolution, but as we will see, the truth lies somewhere in between.

#figure(
  grid(
        columns: 2,
        rows:    1,
        gutter: 1em,
        [ #align(center)[#image("absoloute_space.png", width: 100%)] ],
        [ #align(center)[#image("relative_space.png", width: 100%)] ],
  ),
  caption: [An illustration of two competing historical views on the nature of space and time. _Left:_ Newton's vision of absolute universal time and absolute space, wherein time moves forward at a constant and uniform rate across the universe and space is immobile and uniform. In this model, both time and space can exist independently of objects within, even in an entirely empty universe. _Right:_ Leibniz's view proposed a wherein time and space did not and could not exist independently of the objects used to measure them. Within this model, space is simply a measure of the relative distances between objects, and time is a measure of the relative motion of objects as their relative positions change. In this model, it makes little sense to talk of a universe without objects since time and space do not exist without objects to hold relative positions and velocities.],
) <absolute_time_and_space>

For a good few centuries, Newton's law of universal gravitation stood as our fundamental understanding of gravity, with its impressive descriptive and predictive power. As our measurements of the solar system became more precise, however, a major discrepancy was noted, one that Newton's law failed to describe. The planet Mercury, so close to the sun and so heavily pulled by its gravity, was found to be behaving ever so slightly strangely @mercury_precession. Under Newton's laws, the orbits of the planets should have been ellipses fixed in space, their paths never deviating; what was observed, however, was a precession of that ellipse over time it rotated, processing around the sun by the barest fractions of a degree per century. If true, which it was, the difference was enough to state with confidence that Newton's universal law of gravitation was not a universal and complete description of gravity.

=== Special Relativity <special-relativity-sec>

By the start of the 19#super("th") century, two more thorns in Newton's side had been revealed. Experiments failed to detect a change in the speed of light irrespective of the Earth's motion through space @absoloute_light --- if light behaved as we might expect from ordinary matter, then its measured speed should change depending on whether we are moving toward its source, and hence in opposition to its own direction of motion, or against and in unison. That is not what was observed. Light moved at the same speed no matter how fast you were going when you measured it relative to its source or any other point in the universe. There was no explanation for this behaviour under Newtonian mechanics. The second tantalising contraction arrived when attempting to apply Maxwell's hugely successful equations describing electromagnetism, which proved incompatible with Newtonian mechanics, again in large part because of the requirement for a constant speed of light at all reference frames @maxwells.

In 1905, Einstein proposed his theory of Special Relativity as an extension beyond standard Newtonian mechanics in a successful attempt to rectify the previously mentioned shortcomings @special_relativity. The initial presentation of special relativity was built upon two revolutionary principles, firstly, the speed of light was the same in all reference frames, meaning that no matter how fast you were traveling relative to another body, the speed of light would, to you (and to all observers), appear the same as it always has --- light would move away from you as it always has, unaffected by your apparent velocity. Secondly, and closely related to the first principle, it stated that the laws of physics will act identically in all inertial reference frames. If you are isolated from the outside world by some impenetrable shell, there is no experiment you could perform to determine that you are moving relative to another body --- the only situations in which you could tell the difference between were between different non-inertial reference frames, wherein the shell surrounding you was accelerating. By introducing these postulates, Einstein explained the observations of light-speed measurements and allowed for the consistent application of Maxwell's laws.
 
What special relativity implied was that there was no one true "stationary" reference frame upon which the universe was built, seemingly disproving Newton's ideal of an absolute universe. All inertial frames were created equal. This seemingly innocent fact had strange consequences for our understanding of the nature of space and time. In order for the speed of light to be absolute, space and time must necessarily, if we are living in a sensical universe, be relative -- were they not, then the cause-and-effect nature of the universe would break down. 

Einstein visualized the problem as a train. He imagined an observer standing in a carriage. The observer watched as a light beam bounced back and forth between two mirrors, one on the ceiling, and the other on the floor. The time taken for light to transit this fixed vertical distance is also fixed, and determined by the speed of light and the distance between the mirrors. A second observer stands on a platform a looks into the moving train as it passes. As he watches the light beam bounce between the two mirrors, he sees that it has to take a diagonal path between the mirrors as the train moves along, longer than the vertical path observed in the carriage's reference frame. If we take special relativity to be true, as is implied by all experiments, the speed of light must be constant for both observers. However, in one reference frame, the light must travel a greater distance than in the other. It cannot be the case that the time taken for the photon to travel between the mirrors is the same for the observer on the carriage and the observer on the platform --- their measurements of time must differ in order to preserve the supremacy of the speed of light. The observer on the platform would indeed see time passing on the train more slowly than time on the apparently "stationary" platform around him --- this effect is called *time dilation*, and it has since been experimentally verified.

Similarly, if we orient the mirrors horizontally, so that the light travels along the length of the carriage, a different relativistic effect becomes apparent. The observer on the platform, observing the light's path as longer due to the train's motion, must reconcile this with the constant speed of light. This reconciliation leads to the conclusion that the train, and the distance between the mirrors, appear shorter in the direction of motion from the platform observer's perspective. This phenomenon, where objects in motion appear contracted in the direction of their movement to stationary observers, is known as *length contraction*.

Together, length contraction and time dilation shatter Newton's notions of absolute time and space. It should be remembered, however, that neither the carriage observer nor the platform observer can be said to be in the true stationary reference frame. The observer standing in the station is in the same inertial reference frame as the rest of the Earth, but that doesn't make it any more true. If the observer at the station had a similar setup of mirrors and lasers, and the train occupant looked out at him, the train occupant would observe the same phenomenon. To the passenger, time outside the train appears slowed, and the station shorter than it ought to be. This seems to be a paradox, often known as the twin paradox. What happens if the train later stopped and the two observers were to meet? It is a common misnomer that acceleration must be introduced in order to coincide the two clocks, however, even staying within the regime of special relativity, we can observe an asymmetry between the two observers, in order for the two observers to mean it is a shared reference frame, one of the observers, in this case, the train passenger, must change between reference frames, even if that change is instantaneous. This asymmetry allows us to solve the paradox, but the explanation is a little complex so will not be discussed here.

As alluded to, Special relativity only deals with inertial reference frames, hence it is a "special" case of a larger, cohesive theory --- that theory, developed by Einstein years later, is General Relativity. 

=== General Relativity and Spacetime <general-relativity-sec>

Although the notions of independent and absolute time and space were dislodged by special relativity, it is still possible to describe the new universe illuminated by special relativity as a geometric, all-pervasive 4D geometry inside which the universe sits. Unlike Newton's world, however, space and time are inseparably linked into one joint four-dimensional continuum wherein motion can affect the relative measurements of time and space --- spacetime. Intervals between events are no longer fixed, and observers often can't even agree on which happened first. Distances must be described by a combination of temporal and spatial coordinates, and because all reference frames are equal, all coordinate systems (ways of assigning values to points in spacetime) are also equally valid.

Special relativity deals with flat spacetime, this type of spacetime is known as *Minkowski space*; see @flat for an illustration; though it is non-Euclidian, and its geometries can sometimes be counterintuitive to people used to traveling at pedestrian velocities, it is isotropic and homogeneous.

Einstein realized that by adding deformations to the otherwise flat Minkowski spacetime described by special relativity, you could induce apparent accelerations in particles existing within this spacetime without imparting any forces on the particles at all. Rather than being attracted by some gravitational force, the particles continue to move as they had been, along their natural paths or *geodesics* (the shortest paths between two points in a given geometry, in Euclidian geometry all geodesics are straight lines), but because of the shape of the geometry around them, they can move and generate apparent accelerations concerning each other. This is why it is often stated that gravity is "not a force" --- gravitational attraction is a result of the geometry of the spacetime in which objects exist, rather than because of any accelerations or forces. 

It should be noted that although under general relativity gravity is not described in the same way as the other fundamental forces, it is still useful and valid to describe it as such. We still don't have a unifying theory of all of the forces, so they may end up being more similar than current theories describe.

#figure(
  grid(
        columns: 2,
        rows:    1,
        gutter: 1em,
        [ #align(center)[#image("flat.png", width: 100%)]],
        [ #align(center)[#image("earth.png", width: 100%)] ],
  ),
  caption: [Two illustrative depictions of Einsteins's spacetime. For illustrative purposes, since we are not 4D beings and the paper on which this will be printed very much isn't, the four dimensions of our universe have been compacted down into two. It should also be noted that these illustrations were not generated with correct physical mathematics but only to give an impression of the concepts being described. _Left:_ Minkowski space --- in the absence of any mass, spacetime will not experience any curvature. This is the special case that Einstien's special relativity describes. If we were to place a particle into this environment, it would not experience any acceleration due to gravity. If the particle itself were massive, it would create a distortion in the spacetime, and the spacetime would no longer be considered Minkowski space even though alone it would not experience any acceleration. Often, when dealing with particles of low mass, their effects on the distortion of spacetime are ignored, and we can still treat the scenario with special relativity. _Right:_ Spactime distorted by a massive object, shown in blue. Curved space is described by Einstein's more general theory, General Relativity. In this scenario, we can see how the presence of mass imprints a distortion into the shape of spacetime. Any particles also present in the same universe as the blue object, assuming it has existed indefinitely, will experience an apparent acceleration in the direction of the blue sphere. A beam of light, for example, comprised of photons and entirely massless, would deflect its path when moving past the sphere. Even though light will always travel in a straight line through the vacuum of space, the space itself is distorted; therefore, a straight line path will manifest itself as an apparent attraction toward the sphere. Notice that using Newton's universal law of gravitation, @newtons-law-of-universal-gravitation, the mass of the photon is zero; therefore, it should not experience any gravitational attraction, and indeed, gravitational lensing of the passage of starlight, as it moves past the sun, was one of the first confirmations of Einstein's theory of General Relativity. Were this sphere several thousand kilometres in diameter, any lifeforms living on its surface, which would appear essentially flat at small scales, would experience a pervasive and everpresent downward force. Note that the mass of the object is distributed throughout its volume, so in regions near the centre of the sphere, the spacetime can appear quite flat, as equal amounts of mass surround it from all directions. ],
) <flat>

Observing that deformations in spacetime would cause apparent accelerations akin to gravity, the natural jump to make is that massive objects that have gravity deform spacetime. The more massive the object, the larger the gravitational well created in spacetime, and the more negative the gravitational potential energy of an object within that gravity well. The more dense the object, the steeper the gravity well, and the stronger the apparent gravitational attraction. See @gravitaional-potentials for an illustration. 

What we experience as the force of gravity when standing on the surface of a massive body like Earth, is an upward acceleration caused by the electromagnetic force of the bonds between atoms within the Earth that exert upward pressure on the soles of our feet. We know we are accelerating upward because we are not in freefall, which would be the case if gravity was a force that was balanced against the force of the planet below. Our bodies, and all particles, simply wish to continue on their geodesic paths, and in the absence of any other forces, that path would be down toward the centre of the Earth.

Perhaps not the first question to arise, but certainly one that will come up eventually, would be, what happens if we keep increasing the density of a massive object? Is there a physical limit to the density of an object? Would gravity keep getting steeper and steeper? The mathematical solution to this question was answered by Karl Schwarzschild, who found solutions to Einstein's equations for both a signal point and a spherical mass. It was found that the single-point solution caused, strange mathematical results at a particular radius, known as the Schwarzschild radius, including infinities. It was assumed by some that the solution was theoretical alone and such an object could not exist in nature. 

It was later discovered that there were indeed physical scenarios in which matter could become so compressed there was nothing to stop it from collapsing into what can mathematically be described as a single point, without no repulsive forces strong enough to prevent gravitational collapse. Such objects would create a gravitational well so steep that light itself would not be able to escape, and since light travels at the fastest possible velocity, nothing else could either. It was from this complete state of darkness that these objects received their name --- black holes. See @gravitaional-potentials for a depiction of a black hole.

#figure(
  grid(
        columns: 2,
        rows:    1,
        gutter: 1em,
        [ #align(center)[#image("earth_moon.png", width: 100%)] ],
        [ #align(center)[#image("black_hole.png", width: 100%)] ],
  ),
  caption: [Two further depictions of spacetime. Again, these images are a 2D representation of the 4D spacetime, and they were generated without correct physical descriptions but for illustrative purposes alone. _Left:_ Two objects, one in blue with a lesser mass and one in yellow with a greater mass. Objects with a larger mass distort spacetime to a greater extent, so objects close to the yellow sphere will experience a stronger apparent acceleration as the space curves and the objects continue to move on a straight line. In this scenario, if stationary, the yellow and blue objects will accelerate and move toward each other and, without outside interference, inevitably collide. However, if either the blue or yellow ball is given an initial velocity perpendicular to the direction of the other sphere so that its straight-line path orbits the other sphere, they can remain equidistant from each other in a stable orbit for potentially very long periods of time. As we will see, this orbit will eventually lose energy and decay, but depending on the masses of the two objects, this could take an extremely long time. _Right:_ A black hole. Thus far, we have assumed that the mass of the yellow and blue objects are evenly distributed through their volume, so the spacetime at the very centre of the object is, at its limit, entirely flat. In many scenarios, this is a physically possible arrangement of matter, as although gravity pulls on every particle within the object, pulling it toward the centre, it is a very weak pull compared to the other forces of nature, which push back out and stop the particles continuing on their naturally preferred trajectory. This prevents a complete collapse of the object. Gravity, however, has one advantage on its side, and that is that there is no negative mass, only positive, so whereas large bodies tend to be electrically neutral as positive and negative charges cancel each other out, gravity always grows stronger. If enough mass congregates in the same place, or if the forces pushing matter away from the centre stop, there's nothing to stop gravity from pulling every particle in that object right to the centre, right into a singular point of mass with infinite density known as the singularity. As this collapse occurs, the curvature of spacetime surrounding the object gets stronger and stronger, eventually reaching the point where within a region around the singularity, known as the event horizon, all straight-line paths point toward the singularity. Meaning that no matter your speed, no matter your acceleration, you cannot escape, even if you are light itself. Consequently, no information can ever leave the event horizon, and anything within is forever censored from the rest of the universe.]
) <gravitaional-potentials>

== Orbits are Not Forever

In both Newtonian mechanics and General relativity it is possible to describe two objects that are in an excited state of constant motion, each object gravitational bound to the other but never directly touching, similar to an electron caught in an atomic orbital.  As expected, both theories are correctly describing existent phenomena. When in this state, the objects are said to be *orbiting* each other. If one object is significantly smaller than the other, then it is the smaller is usually referred to as the orbiter, and the larger the orbited, although in reality they both exert equal force on each other and the centre of their orbit will never quite align with the centre of the more massive object, even if it is negligibly close.

It is also quite easy to arrive the notion of an orbit starting from everyday princples.

#figure(
  image("waves.png", width: 70%),
  caption: [A depiction of the region of spacetime surrounding two inspiraling black holes. The spacetime grid visible is a 2D representation of the true 4D nature of our universe as described by general relativity. This depiction was not produced by an accurate simulation but was constructed as a visual aid alone. Two massive objects can orbit each other if they have sufficient perpendicular velocity to each other; this is a natural state for objects to find themselves trapped in because the chances of direct collisions between objects are low, and any objects that find themselves gravitationally bound together and do not experience a direct collision will eventuate in an orbit. The same is true for black holes; whether they form from pairs of massive stars that both evolve into black holes after the end of their main sequence lives or whether they form separately and through dynamical interaction, end up adjoined and inseparable, the occurrence of two black holes orbiting is not inconceivable. Over time, small amounts of energy will leak from these binaries; ripples are sent out through the cosmos, carrying energy away from the system and gradually reducing the separation between the companions. As they get closer, the curvature of the spacetime they occupy increases and thus, their acceleration toward each other grows. They speed up, and the amount of energy that is lost through gravitational radiation increases, further increasing the speed of their inspiral in an ever-accelerating dance. If they started out just close enough, this process would be enough to merge them within the lifetime of the universe; they will inevitably collide with an incredible release of energy out through spacetime as powerful gravitational waves. It is these waves, these disturbances in the nature of length and time itself, that we can measure here on Earth using gravitational wave observatories.]
) <waves>

== Detecting Gravity

In order to sense disturbances in the force ...

=== Interfereometer Noise  <interferometer_noise_sec>