= Gravitational Waves
\
Since time immemorial, humanity has gazed at the stars. With wonder rooted deep in their minds, they imagined strange and divine mechanisms in order to try and make sense of what they saw. Over the millennium, the vast skies have revealed much about their working, and with ever-improving tools, we have come much closer to understanding their mysteries, but there is still much to be uncovered. It is unclear exactly how deep the truth lies. Perhaps we have, but only scratched at the surface. The depths are so vast we simply do not know.

Almost all of that knowledge, all of that understanding and academia has been built upon the observation of just a single type of particle. Until very recently, the only information we had about the world above us came from light, and although the humble photon has taught us a great deal about the scope of our universe, the discovery of new messengers promises pristine, untapped wells of science. It has only been in the last century that we have achieved the technological prowess to detect any other extraterrestrial sources of data except that which fell to us as meteors. We have brought rocks home from the moon. We study data sent back from probes shot out across the solar system and even ones that have peaked just beyond the sun's mighty sphere of influence. We have seen neutrinos, tiny, almost massless particles that pass through entire planets more easily than birds through the air, and, most recently of all, we have seen the skin of space itself quiver --- gravitational waves, the newest frontier in astronomy.

Practical gravitational-wave astronomy is in its infancy; compared to the other fields of astrophysics, it has barely left the cradle, with the first confirmed gravitational-wave detection occurring in 2015 @first_detction. Although the field has progressed remarkably quickly since its inception, there is still a lot of work to be done --- a lot of groundwork to be performed whilst we uncover the best ways to deal with the influx of new data that we are presented with. It seems likely, assuming both funding and human civilisation prevail, that work undertaken now will be but the first bricks in a great wall of discovery. New gravitational-wave observatories that are even today being planned will increase our sensitive range by orders of magnitude. With any luck, they will open our ears further to previously undiscovered wonders.

This chapter will introduce a small part of the science of gravitational waves; it will not be an extensive review as many of the particularities are not especially relevant to the majority of the content of this thesis. Instead, this section aims to act as a brief overview to give context to the purpose behind the data-analysis methods presented throughout. We will cover the theoretical underpinning of gravitational waves, as well as a glancing tour through the experiments used to detect them.

== Gravity --- A Brief History of Down
\

Gravity is one of the four fundamental forces of nature, the other three being the electromagnetic force and the strong and weak nuclear forces. It is, in some ways, the black sheep of the interactions, as it is the only one not explained by the standard model of particle physics, which just so happens to be the most accurate theory of physics ever created by human hands (and brains). Luckily, gravity has its own extremely accurate descriptive theory, even if it doesn't like to play well with the others. It has a storied history, which, if you are unfamiliar, is worth skimming for context. 

This thesis is written with the intent to be at least somewhat passable to all; my dad is attempting to read it, but this next subsection is mostly for context, and if you're primarily focused on examining the author, feel free to skip to more relevant time, @general-relativity-sec. I fear the page count may have got somewhat out of hand by the time I'm finished, so I understand your plight.

=== Ye Old Times

In the beginning, men threw rocks at each other and were entirely unsurprised when they hit the floor. Over time, people became more and more confused as to why this was the case. Many philosophers proposed many reasons why one direction should be preferred over all others when it came to the unrestrained motion of an object. For a long time, there was much confusion about the relationship between mass, density, and buoyancy, and the nature and position of various celestial objects. Still, sometime after, we had decided that the Earth was not, in fact, at the centre of the universe and that objects fell at the same speed irrespective of their densities. We reached the time of Sir Issac Newton, and along with him arrived what many would argue was the beginning of modern physics.

The idea of gravity as a concept had been around for many thousands of years at this point, but what Newton did was to formalise the rules by which objects behave under the action of gravity. Newton's universal law of gravitation states that all massive objects in the universe attract all others @principia_mathematica, acting upon each other, much to his displeasure, whether surrounded by a medium or not. Gravity appeared to ignore all boundaries and was described in a simple formula that seemed to correctly predict everything from the motion of the planets (mostly) to the fall of an apple

#set math.equation(numbering: "(2.1)")
$ F = (G m_1 m_2) / r^2 . $ <newtons-law-of-universal-gravitation>

where $F$ is the force along the direction between the two masses, $G$ is the gravitational constant equal to $6.67430(15) times 10^(−1)$, $m_1$ is the mass of the first object, $m_2$ is the mass of the second object, and $r$ is the distance between the two objects. Newton's law of universal gravitation describes the force every massive object in the universe experiences because of every other --- an equal and opposite force proportional to the product of their two masses; see . Though we now know this equation to be an imperfect description of reality, it still holds accurate enough for many applications to this day.

#figure(
  image("newtons_law.png", width: 30%),
  caption: [An illustration of Newton's law of universal gravitation, as described by @newtons-law-of-universal-gravitation. Two particles, here distinguished by their unique masses $m_1$ and $m_2$ are separated by a distance, $r$, are pulled toward each other by the force of gravity acting on each object $F$, each being pulled directly toward the other by a force that is equal and opposite.],
) <newtons_law>

It was also around this time that a fierce debate raged over the nature of space and time. Newton proposed a universal time that ticked whether in the presence of a clock or not and a static, ever-present grid of space that never wavered nor wandered. Both would continue to exist whether the rest of the universe was there or not. Leibniz, on the other hand, argued that space and time were little more than the relations between the positions of objects and sequences of events. If there were no objects, there would be nothing to measure, and there would be no space. If there were no events, there would be nothing to time, and there would be no ticks; see . At the time, they did not come to a resolution, but as we will see, the truth lies somewhere in between.

#figure(
  grid(
        columns: 2,
        rows:    1,
        gutter: 1em,
        [ #align(center)[#image("absoloute_space.png", width: 100%)] ],
        [ #align(center)[#image("relative_space.png", width: 100%)] ],
  ),
  caption: [An illustration of two competing historical views on the nature of space and time. _Left:_ Newton's vision of absolute universal time and absolute space, wherein time moves forward at a constant and uniform rate across the universe and space is immobile and uniform. In this model, both time and space can exist independently of objects within, even in an entirely empty universe. _Right:_ Leibniz's view proposed a wherein time and space did not and could not exist independently of the objects used to measure them. Within this model, space is simply a measure of the relative distances between objects, and time is a measure of the relative motion of objects as their relative positions change. In this model, it makes little sense to talk of a universe without objects since time and space do not exist without objects to hold relative positions and velocities.],
) <absolute_time_and_space>

For a good few centuries, Newton's law of universal gravitation stood as our fundamental understanding of gravity, with its impressive descriptive and predictive power. As our measurements of the solar system became more precise, however, a major discrepancy was noted, one that Newton's law failed to describe. The planet Mercury, so close to the sun and so heavily pulled by its gravity, was found to be behaving ever so slightly strangely. Under Newton's laws, the orbits of the planets should have been ellipses fixed in space, their paths never deviating; what was observed, however, was a precession of that ellipse over time it rotated, processing around the sun by the barest fractions of a degree per century. If true, which it was, the difference was enough to state with confidence that Newton's universal law of gravitation was not a universal and complete description of gravity.

=== General Relativity <general-relativity-sec>

By the start of the 19#super("th") century, two more thorns in Newton's side had been revealed. Experiments failed to detect a change in the speed of light irrespective of the Earth's motion through space --- if light behaved as we might expect from ordinary matter, then its measured speed should change depending on whether we are moving toward its source, and hence in opposition to its own direction of motion, or against and in unison. That is not what was observed. Light moved at the same speed no matter how fast you were going when you measured it relative to its source or any other point in the universe. There was no explanation for this behaviour under Newtonian mechanics. The second tantalising contraction arrived when attempting to apply Maxwell's hugely successful equations describing electromagnetism, which proved incompatible with Newtonian mechanics, again in large part because of the requirement for a constant speed of light at all reference frames.

In 1905, Einstein proposed his theory of Special Relativity as an extension beyond standard Newtonian mechanics in a successful attempt to rectify the previously mentioned shortcomings.

#figure(
  grid(
        columns: 2,
        rows:    1,
        gutter: 1em,
        [ #align(center)[#image("flat.png", width: 100%)]],
        [ #align(center)[#image("earth.png", width: 100%)] ],
  ),
  caption: [Two illustrative depictions of Einsteins's spacetime. For illustrative purposes, since we are not 4D beings and the paper on which this will be printed very much isn't, the four dimensions of our universe have been compacted down into two. It should also be noted that these illustrations were not generated with correct physical mathematics but only to give an impression of the concepts being described. _Left:_ Minkowski space --- in the absence of any mass, spacetime will not experience any curvature. This is the special case that Einstien's special relativity describes. If we were to place a particle into this environment, it would not experience any acceleration due to gravity. If the particle itself were massive, it would create a distortion in the spacetime, and the spacetime would no longer be considered Minkowski space even though alone it would not experience any acceleration. Often, when dealing with particles of low mass, their effects on the distortion of spacetime are ignored, and we can still treat the scenario with special relativity. _Right:_ Spactime distorted by a massive object, shown in blue. Curved space is described by Einstein's more general theory, General Relativity. In this scenario, we can see how the presence of mass imprints a distortion into the shape of spacetime. Any particles also present in the same universe as the blue object, assuming it has existed indefinitely, will experience an apparent acceleration in the direction of the blue sphere. A beam of light, for example, comprised of photons and entirely massless, would deflect its path when moving past the sphere. Even though light will always travel in a straight line through the vacuum of space, the space itself is distorted; therefore, a straight line path will manifest itself as an apparent attraction toward the sphere. Notice that using Newton's universal law of gravitation, @newtons-law-of-universal-gravitation, the mass of the photon is zero; therefore, it should not experience any gravitational attraction, and indeed, gravitational lensing of the passage of starlight, as it moves past the sun, was one of the first confirmations of Einstein's theory of General Relativity. Were this sphere several thousand kilometres in diameter, any lifeforms living on its surface, which would appear essentially flat at small scales, would experience a pervasive and everpresent downward force. Note that the mass of the object is distributed throughout its volume, so in regions near the centre of the sphere, the spacetime can appear quite flat, as equal amounts of mass surround it from all directions. ],
) <flat>

#figure(
  grid(
        columns: 2,
        rows:    1,
        gutter: 1em,
        [ #align(center)[#image("earth_moon.png", width: 100%)] ],
        [ #align(center)[#image("black_hole.png", width: 100%)] ],
  ),
  caption: [Two further depictions of spacetime. Again, these images are a 2D representation of the 4D spacetime, and they were generated without correct physical descriptions but for illustrative purposes alone. _Left:_ Two objects, one in blue with a lesser mass and one in yellow with a greater mass. Objects with a larger mass distort spacetime to a greater extent, so objects close to the yellow sphere will experience a stronger apparent acceleration as the space curves and the objects continue to move on a straight line. In this scenario, if stationary, the yellow and blue objects will accelerate and move toward each other and, without outside interference, inevitably collide. However, if either the blue or yellow ball is given an initial velocity perpendicular to the direction of the other sphere so that its straight-line path orbits the other sphere, they can remain equidistant from each other in a stable orbit for potentially very long periods of time. As we will see, this orbit will eventually lose energy and decay, but depending on the masses of the two objects, this could take an extremely long time. _Right:_ A black hole. Thus far, we have assumed that the mass of the yellow and blue objects are evenly distributed through their volume, so the spacetime at the very centre of the object is, at its limit, entirely flat. In many scenarios, this is a physically possible arrangement of matter, as although gravity pulls on every particle within the object, pulling it toward the centre, it is a very weak pull compared to the other forces of nature, which push back out and stop the particles continuing on their naturally preferred trajectory. This prevents a complete collapse of the object. Gravity, however, has one advantage on its side, and that is that there is no negative mass, only positive, so whereas large bodies tend to be electrically neutral as positive and negative charges cancel each other out, gravity always grows stronger. If enough mass congregates in the same place, or if the forces pushing matter away from the centre stop, there's nothing to stop gravity from pulling every particle in that object right to the centre, right into a singular point of mass with infinite density known as the singularity. As this collapse occurs, the curvature of spacetime surrounding the object gets stronger and stronger, eventually reaching the point where within a region around the singularity, known as the event horizon, all straight-line paths point toward the singularity. Meaning that no matter your speed, no matter your acceleration, you cannot escape, even if you are light itself. Consequently, no information can ever leave the event horizon, and anything within is forever censored from the rest of the universe.]
) <gravitaional-potentials>

== Orbits are Not Forever

#figure(
  image("waves.png", width: 70%),
  caption: [A depiction of the region of spacetime surrounding two inspiraling black holes. The spacetime grid visible is a 2D representation of the true 4D nature of our universe as described by general relativity. This depiction was not produced by an accurate simulation but was constructed as a visual aid alone. Two massive objects can orbit each other if they have sufficient perpendicular velocity to each other; this is a natural state for objects to find themselves trapped in because the chances of direct collisions between objects are low, and any objects that find themselves gravitationally bound together and do not experience a direct collision will eventuate in an orbit. The same is true for black holes; whether they form from pairs of massive stars that both evolve into black holes after the end of their main sequence lives or whether they form separately and through dynamical interaction, end up adjoined and inseparable, the occurrence of two black holes orbiting is not inconceivable. Over time, small amounts of energy will leak from these binaries; ripples are sent out through the cosmos, carrying energy away from the system and gradually reducing the separation between the companions. As they get closer, the curvature of the spacetime they occupy increases and thus, their acceleration toward each other grows. They speed up, and the amount of energy that is lost through gravitational radiation increases, further increasing the speed of their inspiral in an ever-accelerating dance. If they started out just close enough, this process would be enough to merge them within the lifetime of the universe; they will inevitably collide with an incredible release of energy out through spacetime as powerful gravitational waves. It is these waves, these disturbances in the nature of length and time itself, that we can measure here on Earth using gravitational wave observatories.]
) <waves>


== Detecting Gravity

In order to sense disturbances in the force ...

=== Interfereometer Noise  <interferometer_noise_sec>